// flow-typed signature: 5d0c7ae49f594fc1c64f1c503f01ff6b
// flow-typed version: <<STUB>>/react-native-flags_v^1.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-flags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-flags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-flags/example/FlagExample' {
  declare module.exports: any;
}

declare module 'react-native-flags/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-flags/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/flat/16/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/flat/24/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/flat/32/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/flat/48/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/flat/64/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/flat/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/shiny/16/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/shiny/24/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/shiny/32/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/shiny/48/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/shiny/64/index' {
  declare module.exports: any;
}

declare module 'react-native-flags/flags/shiny/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-flags/example/FlagExample.js' {
  declare module.exports: $Exports<'react-native-flags/example/FlagExample'>;
}
declare module 'react-native-flags/example/index.android.js' {
  declare module.exports: $Exports<'react-native-flags/example/index.android'>;
}
declare module 'react-native-flags/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-flags/example/index.ios'>;
}
declare module 'react-native-flags/flags/flat/16/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/flat/16/index'>;
}
declare module 'react-native-flags/flags/flat/24/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/flat/24/index'>;
}
declare module 'react-native-flags/flags/flat/32/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/flat/32/index'>;
}
declare module 'react-native-flags/flags/flat/48/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/flat/48/index'>;
}
declare module 'react-native-flags/flags/flat/64/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/flat/64/index'>;
}
declare module 'react-native-flags/flags/flat/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/flat/index'>;
}
declare module 'react-native-flags/flags/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/index'>;
}
declare module 'react-native-flags/flags/shiny/16/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/shiny/16/index'>;
}
declare module 'react-native-flags/flags/shiny/24/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/shiny/24/index'>;
}
declare module 'react-native-flags/flags/shiny/32/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/shiny/32/index'>;
}
declare module 'react-native-flags/flags/shiny/48/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/shiny/48/index'>;
}
declare module 'react-native-flags/flags/shiny/64/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/shiny/64/index'>;
}
declare module 'react-native-flags/flags/shiny/index.js' {
  declare module.exports: $Exports<'react-native-flags/flags/shiny/index'>;
}
declare module 'react-native-flags/index' {
  declare module.exports: $Exports<'react-native-flags'>;
}
declare module 'react-native-flags/index.js' {
  declare module.exports: $Exports<'react-native-flags'>;
}
